def teamInfoFromId(id:int):
    nhlTeamsById = {
        1: {'full_name': 'New Jersey Devils', 'abbreviation': 'NJD', 'defunct': False},
        2: {'full_name': 'New York Islanders', 'abbreviation': 'NYI', 'defunct': False},
        3: {'full_name': 'New York Rangers', 'abbreviation': 'NYR', 'defunct': False},
        4: {'full_name': 'Philadelphia Flyers', 'abbreviation': 'PHI', 'defunct': False},
        5: {'full_name': 'Pittsburgh Penguins', 'abbreviation': 'PIT', 'defunct': False},
        6: {'full_name': 'Boston Bruins', 'abbreviation': 'BOS', 'defunct': False},
        7: {'full_name': 'Buffalo Sabres', 'abbreviation': 'BUF', 'defunct': False},
        8: {'full_name': 'Montreal Canadiens', 'abbreviation': 'MTL', 'defunct': False},
        9: {'full_name': 'Ottawa Senators', 'abbreviation': 'OTT', 'defunct': False},
        10: {'full_name': 'Toronto Maple Leafs', 'abbreviation': 'TOR', 'defunct': False},
        11: {'full_name': 'Atlanta Thrashers', 'abbreviation': 'ATL', 'defunct': True},
        12: {'full_name': 'Carolina Hurricanes', 'abbreviation': 'CAR', 'defunct': False},
        13: {'full_name': 'Florida Panthers', 'abbreviation': 'FLA', 'defunct': False},
        14: {'full_name': 'Tampa Bay Lightning', 'abbreviation': 'TBL', 'defunct': False},
        15: {'full_name': 'Washington Capitals', 'abbreviation': 'WSH', 'defunct': False},
        16: {'full_name': 'Chicago Blackhawks', 'abbreviation': 'CHI', 'defunct': False},
        17: {'full_name': 'Detroit Red Wings', 'abbreviation': 'DET', 'defunct': False},
        18: {'full_name': 'Nashville Predators', 'abbreviation': 'NSH', 'defunct': False},
        19: {'full_name': 'St. Louis Blues', 'abbreviation': 'STL', 'defunct': False},
        20: {'full_name': 'Calgary Flames', 'abbreviation': 'CGY', 'defunct': False},
        21: {'full_name': 'Colorado Avalanche', 'abbreviation': 'COL', 'defunct': False},
        22: {'full_name': 'Edmonton Oilers', 'abbreviation': 'EDM', 'defunct': False},
        23: {'full_name': 'Vancouver Canucks', 'abbreviation': 'VAN', 'defunct': False},
        24: {'full_name': 'Anaheim Ducks', 'abbreviation': 'ANA', 'defunct': False},
        25: {'full_name': 'Dallas Stars', 'abbreviation':'DAL', 'defunct': False},
        26: {'full_name': 'Los Angeles Kings', 'abbreviation': 'LAK', 'defunct': False},
        27: {'full_name': 'Pheonix Coyotes', 'abbreviation': 'PHX', 'defunct': True},
        28: {'full_name': 'San Jose Sharks', 'abbreviation': 'SJS', 'defunct': False},
        29: {'full_name': 'Columbus Blue Jackets', 'abbreviation': 'CBJ', 'defunct': False},
        30: {'full_name': 'Minnesota Wild', 'abbreviation': 'MIN', 'defunct': False},
        31: {'full_name': 'Minnesota North Stars', 'abbreviation': 'MNS', 'defunct': True},
        32: {'full_name': 'Quebec Nordiques', 'abbreviation': 'QUE', 'defunct': True},
        33: {'full_name': 'Winnipeg Jets', 'abbreviation': 'WIN', 'defunct': True},
        34: {'full_name': 'Hartford Whalers', 'abbreviation': 'HFD', 'defunct': True},
        35: {'full_name': 'Colorado Rockies', 'abbreviation': 'CLR', 'defunct': True},
        36: {'full_name': 'Ottowa Senators', 'abbreviation': 'SEN', 'defunct': True},
        37: {'full_name': 'Hamilton Tigers', 'abbreviation': 'HAM', 'defunct': True},
        38: {'full_name': 'Pittsburgh Pirates', 'abbreviation': 'PIR', 'defunct': True},
        39: {'full_name': 'Philadelphia Quakers', 'abbreviation': 'QUA', 'defunct': True},
        40: {'full_name': 'Detroit Cougars', 'abbreviation': 'DCG', 'defunct': True},
        41: {'full_name': 'Montreal Wanderers', 'abbreviation': 'MWN', 'defunct': True},
        42: {'full_name': 'Quebec Bulldogs', 'abbreviation': 'QBD', 'defunct': True},
        43: {'full_name': 'Montreal Maroons', 'abbreviation': 'MMR', 'defunct': True},
        44: {'full_name': 'New York Americans', 'abbreviation': 'NYA', 'defunct': True},
        45: {'full_name': 'St. Louis Eagles', 'abbreviation': 'SLE', 'defunct': True},
        46: {'full_name': 'Oakland Seals', 'abbreviation': 'OAK', 'defunct': True},
        47: {'full_name': 'Atlanta Flames', 'abbreviation': 'AFM', 'defunct': True},
        48: {'full_name': 'Kansas City Scouts', 'abbreviation': 'KCS', 'defunct': True},
        49: {'full_name': 'Cleveland Barons', 'abbreviation': 'CLE', 'defunct': True},
        50: {'full_name': 'Detroit Falcons', 'abbreviation': 'DFL', 'defunct': True},
        51: {'full_name': 'Brooklyn Americans', 'abbreviation': 'BRK', 'defunct': True},
        52: {'full_name': 'Winnipeg Jets', 'abbreviation': 'WPG', 'defunct': False},
        53: {'full_name': 'Arizona Coyotes', 'abbreviation': 'ARI', 'defunct': True},
        54: {'full_name': 'Las Vegas Golden Knights', 'abbreviation': 'VGK', 'defunct': False},
        55: {'full_name': 'Seattle Kraken', 'abbreviation': 'SEA', 'defunct': False},
        56: {'full_name': 'California Golden Seals', 'abbreviation': 'CGS', 'defunct': True},
        57: {'full_name': 'Toronto Arenas', 'abbreviation': 'TAN', 'defunct': True},
        58: {'full_name': 'Toronto St. Patricks', 'abbreviation': 'TSP', 'defunct': True},
        59: {'full_name': 'Utah Hockey Club', 'abbreviation': 'UTA', 'defunct': True},
        68: {'full_name': 'Utah Mammoth', 'abbreviation': 'UTA', 'defunct': False},
        70: {'full_name': 'To be determined', 'abbreviation': 'TBD', 'defunct': True},
        99: {'full_name': 'NHL', 'abbreviation': 'NHL', 'defunct': True}
    }
    return nhlTeamsById[id]