from custom_attributes.realX import realX
from custom_attributes.manAdv import manAdv
from math import atan2, degrees

def modelCriteria(shot:dict):
    return {
        'adjX': realX(shot)-11,
        'adjY': abs(shot['details']['yCoord']),
        'adjXSquared': (realX(shot)-11)**2,
        'adjYSquared': (shot['details']['yCoord'])**2,
        'angle': degrees(atan2(abs(shot['details']['yCoord']), 100-realX(shot))),
        'awayTeam': 1 if shot['details']['eventOwnerTeamId'] == shot['awayTeamId'] else 0,
        'distance': (((89-realX(shot)) + shot['details']['yCoord']**2)**0.5).real,
        'distanceSquared': (89-realX(shot)) + shot['details']['yCoord']**2,
        'homeTeam': 1 if shot['details']['eventOwnerTeamId'] == shot['homeTeamId'] else 0,
        'lastEventBlockedShot': 1 if shot['previousEvent'] == 'blocked-shot' else 0,
        'lastEventDelayedPenalty': 1 if shot['previousEvent'] == 'delayed-penalty' else 0,
        'lastEventFaceoff': 1 if shot['previousEvent'] == 'faceoff' else 0,
        'lastEventFailedShotAttempt': 1 if shot['previousEvent'] == 'failed-shot-attempt' else 0,
        'lastEventGameEnd': 1 if shot['previousEvent'] == 'game-end' else 0,
        'lastEventGiveaway': 1 if shot['previousEvent'] == 'giveaway' else 0,
        'lastEventGoal': 1 if shot['previousEvent'] == 'goal' else 0,
        'lastEventHit': 1 if shot['previousEvent'] == 'hit' else 0,
        'lastEventMissedShot': 1 if shot['previousEvent'] == 'missed-shot' else 0,
        'lastEventPenalty': 1 if shot['previousEvent'] == 'penalty' else 0,
        'lastEventPeriodEnd': 1 if shot['previousEvent'] == 'period-end' else 0,
        'lastEventPeriodStart': 1 if shot['previousEvent'] == 'period-start' else 0,
        'lastEventShotOnGoal': 1 if shot['previousEvent'] == 'shot-on-goal' else 0,
        'lastEventStoppage': 1 if shot['previousEvent'] == 'stoppage' else 0,
        'lastEventTakeaway': 1 if shot['previousEvent'] == 'takeaway' else 0,
        'periodTypeOT': 1 if shot['periodDescriptor']['periodType'] == 'OT' else 0,
        'periodTypeREG': 1 if shot['periodDescriptor']['periodType'] == 'REG' else 0,
        'rebound': 1 if 0 <= shot['timeSinceLastShot'] <= 3 else 0,
        'shotTypeBackhand': 1 if shot['details']['shotType'] == 'backhand' else 0,
        'shotTypeBat': 1 if shot['details']['shotType'] == 'bat' else 0,
        'shotTypeBetweenLegs': 1 if shot['details']['shotType'] == 'between-legs' else 0,
        'shotTypeCradle': 1 if shot['details']['shotType'] == 'cradle' else 0,
        'shotTypeDeflected': 1 if shot['details']['shotType'] == 'deflected' else 0,
        'shotTypePoke': 1 if shot['details']['shotType'] == 'poke' else 0,
        'shotTypeSlap': 1 if shot['details']['shotType'] == 'slap' else 0,
        'shotTypeSnap': 1 if shot['details']['shotType'] == 'snap' else 0,
        'shotTypeTipIn': 1 if shot['details']['shotType'] == 'tip-in' else 0,
        'shotTypeWrapAround': 1 if shot['details']['shotType'] == 'wrap-around' else 0,
        'shotTypeWrist': 1 if shot['details']['shotType'] == 'wrist' else 0,
        'timeSinceLastShot': shot['timeSinceLastShot']
    }
